export const allMoviesData = [
  { id: 0, genre: 'Action', img: 'img/action.jpg' },
  { id: 1, genre: 'Comedy', img: 'img/comedy.jpg' },
  { id: 2, genre: 'Drama', img: 'img/drama.jpg' },
  { id: 3, genre: 'Fantasy', img: 'img/fantasy.jpg' },
  { id: 4, genre: 'Horror', img: 'img/horror.jpg' },
  { id: 5, genre: 'Musical', img: 'img/musical.jpg' },
  { id: 6, genre: 'Mystery', img: 'img/mystery.jpg' },
  { id: 7, genre: 'Romance', img: 'img/romance.jpg' },
  { id: 8, genre: 'Sci-fi', img: 'img/scifi.jpg' },
  { id: 9, genre: 'Sports', img: 'img/sports.jpg' },
  { id: 10, genre: 'Thriller', img: 'img/thriller.jpg' },
  { id: 11, genre: 'War', img: 'img/war.jpg' },
  { id: 12, genre: 'Western', img: 'img/western.jpg' },
];
